permalink: /:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Moilker橱窗"
description: "Moilker主页"

# 地址设置
baseurl: ""
url: "http://127.0.0.1:4000"

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil
highlighter: pygments

# 分页设置
paginate: 10
paginate_path: "page/:num"