permalink: /:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Moilker橱窗"
description: "Moilker主页"

# 地址设置
baseurl: ""
url: "http://moilk.org"

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: false
highlighter: pygments

# 分页设置
paginate: 6
paginate_path: "project/page:num"