permalink: /:year/:month/:day/:title
exclude: ['.git']
name: "Moilker橱窗"
description: "Moilker主页"

# 地址设置
baseurl: ""
url: "https://moilk.org"

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: false
highlighter: rouge

# 分页设置
paginate: 6
paginate_path: "project/page:num"

# GitMent设置
gitment:
  enable: true
  githubID: MoilkNepho
  repo: MoilkNepho.github.io
  ClientID: 39587457ab8aabd98d18
  ClientSecret: 14768f3ef851ddc213cd12c44655d10dd1dc025f
  lazy: true