permalink: /:year/:month/:day/:title/

name: "Moilker橱窗"
description: "Moilker主页"

# 地址设置
baseurl: ""
url: "http://duras.wang"

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil
highlighter: pygments

# 分页设置
paginate: 7
paginate_path: "page:num"